[metadata]
name = semanticdrift
version = 0.1.0

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
install_requires =
    pyyaml>=6.0

[options.packages.find]
where = src

[options.extras_require]
dev =
    pytest>=7.4
    cosmic-ray>=8.7
    pycparser>=2.21

[options.entry_points]
console_scripts =
    semanticdrift = semanticdrift.cli:main
